services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  migrate:
    image: migrate/migrate
  example:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    expose:
      - "8080"
    ports:
      - "8080"
    entrypoint: ["/app", "start", "--logging_level=info"]
