name: Go Monorepo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - 01-simple-k8s-application
          - 02-simple-k8s-fiber-app
          - 03-k8s-fiber-sqlc

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Cache dependencies for each module
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.sum', matrix.module)) }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: |
          cd ${{ matrix.module }}
          go mod tidy

      # Run tests
      - name: Run tests
        run: |
          cd ${{ matrix.module }}
          go test ./...
